### ISSUE TITLE
Problem with docker installation

### ISSUE THREAD

**Issue by prathusha94** [Maluuba/newsqa#23]
I have been trying to follow the Docker installation steps but after running the following command 
`docker run --rm -it -v ${PWD}:/usr/src/newsqa --name newsqa maluuba/newsqa python maluuba/newsqa/data_generator.py
`
I get this error : 
`Traceback (most recent call last):
  File "maluuba/newsqa/data_generator.py", line 8, in <module>
    from simplify import simplify
  File "/usr/src/newsqa/maluuba/newsqa/simplify.py", line 5, in <module>
    import pandas as pd
ImportError: No module named pandas`

But I see that the docker file has a command to install pandas>=0.19.2 so I'm not sure what I'm doing wrong. I have never worked with docker before so would really appreciate any help

Thank You !

**Comment by juharris** [comment]
I'm trying this again on my machine and I first removed all old containers and images.
In the meantime, did you first run both:
```
docker build -t maluuba/newsqa .
docker run --rm -it -v ${PWD}:/usr/src/newsqa --name newsqa maluuba/newsqa
```
?

**Comment by juharris** [comment]
Sorry. Confirmed it happens for me too. I'll look into this.

**Comment by juharris** [comment]
Here's the right command: 
```bash
docker run --rm -it -v ${PWD}:/usr/src/newsqa --name newsqa maluuba/newsqa /bin/bash --login -c 'python maluuba/newsqa/data_generator.py'
```
I'll push a correction to the README soon.

**Comment by prathusha94** [comment]
@juharris Sorry I forgot to update the solution ! Changing the command worked for me too !
I have another question though , the "Split_data" folder doesn't seem to be created after executing the above command !

<img width="576" alt="screenshot 2018-11-19 at 3 33 11 pm" src="https://user-images.githubusercontent.com/37677121/48733376-7c123500-ec10-11e8-81b4-88178c923200.png">
I don't see any errors in here but I'm unable to find the folder with dev and test.csv ! Would really appreciate if you could check with this. 

Thank you !

**Comment by juharris** [comment]
Great I'm glad that helped.
The `split_data` folder should be in the root of you repo (the folder you're running the commands from).

**Comment by prathusha94** [comment]
> Great I'm glad that helped.
> The `split_data` folder should be in the root of you repo (the folder you're running the commands from).

I just did tried the "ls" command as well from the root of the repository(that's where I'm executing all the commands from) but I still don't see it ! 
<img width="627" alt="screenshot 2018-11-19 at 3 43 12 pm" src="https://user-images.githubusercontent.com/37677121/48733885-d95ab600-ec11-11e8-8b4a-236a34a45816.png">

Since you just ran the command on your system too , I wondering if you could find it on yours !
I'm gonna clone the repository again and start everything from scratch but in case that doesn't work , is there any other way I can get the "dev.csv" and "train.csv" files ?

**Comment by juharris** [comment]
Oh it looks like the previous command stopped early for some reason. Try running it again.

It should have shown an error but one issue is that it could be that Docker doesn't have enough memory.

**Comment by juharris** [comment]
Here's what I see when the command finishes properly:
```
(3/3) - Unpacking tokenized file to `/usr/src/newsqa/maluuba/newsqa/newsqa-data-tokenized-v1.csv`
Unpacking: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120k/120k [03:58<00:00, 503 questions/s][INFO] 2018-11-19 21:05:41,398 - tokenize_dataset.py::unpack
Writing to `/usr/src/newsqa/maluuba/newsqa/newsqa-data-tokenized-v1.csv`.
[INFO] 2018-11-19 21:05:55,962 - data_processing.py::load_combined
Loading data from `/usr/src/newsqa/maluuba/newsqa/newsqa-data-tokenized-v1.csv`...
Adjusting story texts: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120k/120k [00:02<00:00, 44.9k questions/s][INFO] 2018-11-19 21:06:05,985 - split_dataset.py::split_data
Loading story ID's split.
Splitting data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120k/120k [00:01<00:00, 104k questions/s][INFO] 2018-11-19 21:06:07,271 - split_dataset.py::split_data
Writing split data to split_data
[INFO] 2018-11-19 21:06:07,272 - split_dataset.py::_write_to_csv
Writing 92549 rows to split_data/train.csv
[INFO] 2018-11-19 21:06:21,834 - split_dataset.py::_write_to_csv
Writing 5166 rows to split_data/dev.csv
[INFO] 2018-11-19 21:06:22,729 - split_dataset.py::_write_to_csv
Writing 5126 rows to split_data/test.csv
```
