### ISSUE TITLE
newsqa-data-v1.csv Not Found

### ISSUE THREAD

**Issue by vaiibhavgupta** [Maluuba/newsqa#43]
Hi,

On running `python maluuba/newsqa/data_generator.py`, I am getting following error - 

```
Traceback (most recent call last):
  File "maluuba/newsqa/data_generator.py", line 30, in <module>
    newsqa_data = NewsQaDataset(args.cnn_stories_path, args.dataset_path)
  File "/newsqa-dataset/newsqa/maluuba/newsqa/data_processing.py", line 80, in __init__
    "\n See the README in the root of this repo for more details." % dataset_path)
Exception: `/newsqa-dataset/newsqa/maluuba/newsqa/newsqa-data-v1.csv` was not found.
For legal reasons, you must first accept the terms and download the dataset from https://msropendata.com/datasets/939b1042-6402-4697-9c15-7a28de7e1321
 See the README in the root of this repo for more details.
```

Any help is much appreciated.

**Comment by vaiibhavgupta** [comment]
So, we need to unzip the .tar file as stated otherwise in the repo.
